env:
  
sudo: false
language: java
jdk:
  - oraclejdk8
#  - openjdk8 not supported, see https://github.com/travis-ci/travis-ci/issues/1647
branches:
  only:
    - master
install: /bin/true
script:
  - "mvn install -Dmaven.test.skip=false"
notifications:
  email:
    recipients:
      - amit@informatik.uni-leipzig.de
      - hellmann@informatik.uni-leipzig.de
    on_success: change
    on_failure: change

