env:
  
sudo: false
language: java
jdk:
  - oraclejdk8
#  - openjdk8 not supported, see https://github.com/travis-ci/travis-ci/issues/1647
branches:
  only:
    - master
    - dev
    - coverity_scan
install: /bin/true
script:
  - "cd tools/backend"
  - "mvn clean install"
  - "bin/validate.sh"
  - "cd .."
notifications:
  email:
    recipients:
      - amit@informatik.uni-leipzig.de
    on_success: change
    on_failure: change

